# Generated by Django 4.0.5 on 2022-08-10 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_room_message_curriculum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Forum',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='room',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='forum',
        ),
    ]
