# Generated by Django 4.0.5 on 2022-08-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_room_forum_rename_room_curriculum_forum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='name',
        ),
    ]
