# Generated by Django 4.0.5 on 2022-08-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_curriculum_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['created', 'updated']},
        ),
    ]
