# Generated by Django 4.0.5 on 2022-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_user_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
